### ISSUE TITLE
Issues on IDA 6.8 when trying to execute `database.get.info` due to the `database.config.__nw_init_info_structure__` notification not being executed.

### ISSUE THREAD

**Issue by gool123456** [arizvisa/ida-minsc#106]
Hi, @arizvisa , I tested another problem at old ida,  the command will have an error in the string or array data :

at byte_3138BC    :

.text:003138BC byte_3138BC     DCB 0
.text:003138BD                 DCB 0x20
.text:003138BE                 DCB    0
.text:003138BF                 DCB 0x6D ; m
.text:003138C0                 DCB    0
.text:003138C1                 DCB    4
.text:003138C2                 DCB    0
.text:003138C3                 DCB    0
.text:003138C4                 DCB 0x11
.text:003138C5                 DCB    0
.text:003138C6                 DCB 0x6D ; m
.text:003138C7                 DCB    0

I shell command **db.get.info()** , this show error , I want see this ea type,  
So I want to define this as an array and **display Indexs**. Is there such a method in ida-minsc? because you can find this option manually in ida with Ctrl+*.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 290, in database.info
    return f(*arguments, **keywords)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 5027, in info
    return cls.info(ui.current.address())
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 290, in database.info
    return f(*arguments, **keywords)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 5032, in info
    return type(ea)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 290, in database.__new__
    return f(*arguments, **keywords)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 2853, in __new__
    res = idaapi.guess_tinfo(ea, ti) if idaapi.__version__ < 7.0 else idaapi.guess_tinfo(ti, ea)
  File "D:\tools\IDA_Pro_v6.8_and_Hex-Rays_Decompiler_(ARM,x64,x86)_Hskyre\python\idaapi.py", line 35611, in guess_tinfo
    return _idaapi.guess_tinfo(*args)
TypeError: guess_tinfo expected 3 arguments, got 2

**Comment by arizvisa** [comment]
You can define it as an array with `db.set.array`, and fetch it with `db.get.array`. Although, I don't know of any options that enable indices.

**Comment by arizvisa** [comment]
@gool123456, what commit of ida-minsc are you on? None of the line numbers you gave me correspond to the master branch from the repository..

Line #5027 of database.py is https://github.com/arizvisa/ida-minsc/blob/5a3f7425efd8e4ea091c243069fc908d3da61018/base/database.py#L5027
Line #5032 of database.py is https://github.com/arizvisa/ida-minsc/blob/5a3f7425efd8e4ea091c243069fc908d3da61018/base/database.py#L5032
Line #2853 of database.py is https://github.com/arizvisa/ida-minsc/blob/5a3f7425efd8e4ea091c243069fc908d3da61018/base/database.py#L2853

**Comment by gool123456** [comment]
@arizvisa I using **ida-minsc-GH-68** for the old ida (This version is more compatible)

**If I use ida-minsc-master it will give a new error :
This instruction cannot pass
 Python -> opv1 = ins.op(pre_addr, 0)**

**ida-minsc-master** error:
Script Default snippet error: Traceback (most recent call last):
  File "<string>", line 195, in <module>
  File "<string>", line 185, in main
  File "<string>", line 101, in Find_s1
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 337, in instruction.op
    return f(*arguments, **keywords)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\instruction.py", line 462, in op
    return __optype__.decode(ea, res)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\instruction.py", line 79, in decode
    return res(ea, op)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\instruction.py", line 1449, in register
    return architecture.by_indextype(res, get_dtype_attribute(op))
NameError: global name 'architecture' is not defined


But this command **db.get.info** will be wrong in both versions :( ..

**Comment by gool123456** [comment]
@arizvisa  Sorry, I was wrong, the shortcut to define an array is Shift+* 

You cant see dialog has Options :

---- Options-----------
[ *] Use "dup" construct
[  ] Signed elements
[ *] **Display indexes**   <-
[ *] Create as array

------------------------

**Comment by arizvisa** [comment]
> @arizvisa I using **ida-minsc-[GH-68](https://github.com/arizvisa/ida-minsc/issues/68)** for the old ida (This version is more compatible)
> 
> **If I use ida-minsc-master it will give a new error : This instruction cannot pass Python -> opv1 = ins.op(pre_addr, 0)**
> 
> **ida-minsc-master** error:
> Script Default snippet error: Traceback (most recent call last):
> File "", line 195, in
> File "", line 185, in main
> File "", line 101, in Find_s1
> File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base_utils.py", line 337, in instruction.op
> return f(*arguments, **keywords)
> File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\instruction.py", line 462, in op
> return **optype**.decode(ea, res)
> File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\instruction.py", line 79, in decode
> return res(ea, op)
> File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\instruction.py", line 1449, in register
> return architecture.by_indextype(res, get_dtype_attribute(op))
> NameError: global name 'architecture' is not defined
> 
> But this command **db.get.info** will be wrong in both versions :( ..

Okay so if `architecture` is not defined, then that means the `instruction.__newprc__` hook is not being executed.
When you start IDA and open up the database, you should see the following line executed.

https://github.com/arizvisa/ida-minsc/blob/f5a283f5b9fd498a3da60fa3cb43f249fa8288a0/base/instruction.py#L2432

Which outputs:
```
WARNING:root:Initialized IDA database v700 for 32-bit little-endian userspace library.
WARNING:root:Detected processor module : Intel architecture 32-bit (0)
```

Can you add a print statement to the following line? It should be assigning the notification hook to initialize `architecture`.
https://github.com/arizvisa/ida-minsc/blob/f5a283f5b9fd498a3da60fa3cb43f249fa8288a0/misc/hooks.py#L1087

**Comment by arizvisa** [comment]
Apparently there was an instance of `idaapi.guess_tinfo2` that was missed in the function module, this was fixed in commit 9fd4fd6868548a7371a3945114d195eb38fb4152.

**Comment by gool123456** [comment]
db.get.info() Okay !

architecture is not defined, because used new ida-minsc-master package open up the database , shows :

Loading processor module D:\tools\IDA_Pro_v6.8_and_Hex-Rays_Decompiler_(ARM,x64,x86)_Hskyre\procs\arm.w32 for ARM...OK
Loading type libraries...
Autoanalysis subsystem has been initialized.
[DEBUG] Demangled names have been initialized
[Info] Collecting information about imports
[Warning] Failed to get import module name for #0
[Info] Done...
CRITICAL:root:internal.interface.prioritynotification.callback(1, 1) : Callback for notification (0x1) with priority (-30) raised an exception while executing <bound method type.__nw_init_info_structure__ of <class 'database.config'>>
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : Traceback (notification (0x1) was hooked at)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\misc\hooks.py", line 1115, in ida_is_busy_sucking_cocks
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     make_ida_not_suck_cocks(idaapi.NW_INITIDA)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\misc\hooks.py", line 1096, in make_ida_not_suck_cocks
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     idaapi.__notification__.add(idaapi.NW_OPENIDB, database.config.__nw_init_info_structure__, -30)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : 
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : Traceback (most recent call last):
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_interface.py", line 382, in closure
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     result = callable(*parameters)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 92, in __nw_init_info_structure__
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     return cls.__init_into_structure__(idp_modname)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : AttributeError: type object 'config' has no attribute '__init_into_structure__'
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : 
Database for file 'libBenzHD.so.fixed_41B35000' has been loaded.
Compiling file 'D:\tools\IDA_Pro_v6.8_and_Hex-Rays_Decompiler_(ARM,x64,x86)_Hskyre\idc\ida.idc'...
Executing function 'main'...

**Comment by arizvisa** [comment]
ah awesome. that's a type-o. if you rename `cls.__init_into_structure__` to `cls.__init_info_structure__`. I'ma create a PR for it in a second.

**Comment by arizvisa** [comment]
So, PR #111 fixes that type-o that prevents the hook from being executed on older versions of IDA. After correcting that misspelling, let me know any other issues that are occurring for you so that we can squash those bugs too.

But yeah, unless you use the `master` branch I won't be able to find these issues and fix them. So, despite the other branch being more "compatible", that branch was only a bugfix for 1 issue, and not \_all\_ the issues that have been discovered. So please, when you test things make sure you're testing the `master` branch (or GH-76 for PR #84) as none of the other ones are actually supported.

**Comment by arizvisa** [comment]
(Updated the title of this issue to more directly correspond to the problem.)

**Comment by gool123456** [comment]
> ah awesome. that's a type-o. if you rename `cls.__init_into_structure__` to `cls.__init_info_structure__`. I'ma create a PR for it in a second.

Very happy to see this news. 👍

**Comment by gool123456** [comment]
Test master branch , The following message appeared : 

Loading processor module D:\tools\IDA_Pro_v6.8_and_Hex-Rays_Decompiler_(ARM,x64,x86)_Hskyre\procs\arm.w32 for ARM...OK
Loading type libraries...
Autoanalysis subsystem has been initialized.
[DEBUG] Demangled names have been initialized
[Info] Collecting information about imports
[Warning] Failed to get import module name for #0
[Info] Done...
CRITICAL:root:internal.interface.prioritynotification.callback(1, 1) : Callback for notification (0x1) with priority (-30) raised an exception while executing <bound method type.__nw_init_info_structure__ of <class 'database.config'>>
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : Traceback (notification (0x1) was hooked at)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\misc\hooks.py", line 1115, in ida_is_busy_sucking_cocks
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     make_ida_not_suck_cocks(idaapi.NW_INITIDA)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\misc\hooks.py", line 1096, in make_ida_not_suck_cocks
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     idaapi.__notification__.add(idaapi.NW_OPENIDB, database.config.__nw_init_info_structure__, -30)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : 
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : Traceback (most recent call last):
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_interface.py", line 382, in closure
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     result = callable(*parameters)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 92, in __nw_init_info_structure__
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     return cls.__init_into_structure__(idp_modname)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : AttributeError: type object 'config' has no attribute '__init_into_structure__'
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :

**Comment by arizvisa** [comment]
@gool123456, try PR #111.
That line number (https://github.com/arizvisa/ida-minsc/pull/111/files#) should be read "init_info_structure".

**Comment by gool123456** [comment]
> 
> 
> @gool123456, make sure you're using PR #111. That line number (https://github.com/arizvisa/ida-minsc/pull/111/files#) should be read "init_info_structure". The fix hasn't been merged into master yet because it hasn't been confirmed, and we're not sure yet whether that's the _only_ issue or not.

Using PR #111, ida received messages :

Loading processor module D:\tools\IDA_Pro_v6.8_and_Hex-Rays_Decompiler_(ARM,x64,x86)_Hskyre\procs\arm.w32 for ARM...OK
Loading type libraries...
Autoanalysis subsystem has been initialized.
[DEBUG] Demangled names have been initialized
[Info] Collecting information about imports
[Warning] Failed to get import module name for #0
[Info] Done...
CRITICAL:root:internal.interface.prioritynotification.callback(1, 1) : Callback for notification (0x1) with priority (-30) raised an exception while executing <bound method type.__nw_init_info_structure__ of <class 'database.config'>>
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : Traceback (notification (0x1) was hooked at)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\misc\hooks.py", line 1115, in ida_is_busy_sucking_cocks
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     make_ida_not_suck_cocks(idaapi.NW_INITIDA)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\misc\hooks.py", line 1096, in make_ida_not_suck_cocks
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     idaapi.__notification__.add(idaapi.NW_OPENIDB, database.config.__nw_init_info_structure__, -30)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : 
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : Traceback (most recent call last):
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_interface.py", line 382, in closure
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     result = callable(*parameters)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 92, in __nw_init_info_structure__
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     return cls.__init_info_structure__(idp_modname)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 79, in __init_info_structure__
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     byteorder = "{:s}-endian".format('big' if information.is_be() else 'little')
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : AttributeError: 'idainfo' object has no attribute 'is_be'
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :

**Comment by arizvisa** [comment]
Okay. Give me one second while I go through the documentation to figure out how IDA does it.

**Comment by arizvisa** [comment]
Okay. Try PR #111, again. I added a commit that modifies the `database.config` namespace to explicitly check all of its flags which should hopefully be compatible with IDA 6.8.

**Comment by gool123456** [comment]
@arizvisa Sorry, currently my test is a bit delayed. it say : **AttributeError: 'module' object has no attribute 'LFLG_MSF'**

Loading processor module D:\tools\IDA_Pro_v6.8_and_Hex-Rays_Decompiler_(ARM,x64,x86)_Hskyre\procs\arm.w32 for ARM...OK
Loading type libraries...
Autoanalysis subsystem has been initialized.
[DEBUG] Demangled names have been initialized
[Info] Collecting information about imports
[Warning] Failed to get import module name for #0
[Info] Done...
CRITICAL:root:internal.interface.prioritynotification.callback(1, 1) : Callback for notification (0x1) with priority (-30) raised an exception while executing <bound method type.__nw_init_info_structure__ of <class 'database.config'>>
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : Traceback (notification (0x1) was hooked at)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\misc\hooks.py", line 1115, in ida_is_busy_sucking_cocks
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     make_ida_not_suck_cocks(idaapi.NW_INITIDA)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\misc\hooks.py", line 1096, in make_ida_not_suck_cocks
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     idaapi.__notification__.add(idaapi.NW_OPENIDB, database.config.__nw_init_info_structure__, -30)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : 
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : Traceback (most recent call last):
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_interface.py", line 382, in closure
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     result = callable(*parameters)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 92, in __nw_init_info_structure__
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     return cls.__init_info_structure__(idp_modname)
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 79, in __init_info_structure__
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :     byteorder = "{:s}-endian".format('big' if information.lflags & idaapi.LFLG_MSF else 'little')
WARNING:root:internal.interface.prioritynotification.callback(1, 1) : AttributeError: 'module' object has no attribute 'LFLG_MSF'
WARNING:root:internal.interface.prioritynotification.callback(1, 1) :

**Comment by gool123456** [comment]
@arizvisa ida 6.8 Public LFLG from idaapi.py:

LFLG_PC_FPP = _idaapi.LFLG_PC_FPP
LFLG_PC_FLAT = _idaapi.LFLG_PC_FLAT
LFLG_64BIT = _idaapi.LFLG_64BIT
LFLG_DBG_NOPATH = _idaapi.LFLG_DBG_NOPATH
LFLG_SNAPSHOT = _idaapi.LFLG_SNAPSHOT
LFLG_IS_DLL = _idaapi.LFLG_IS_DLL

**Comment by gool123456** [comment]
my 6.8 python file:
[python6.8.zip](https://github.com/arizvisa/ida-minsc/files/5790424/python6.8.zip)

**Comment by arizvisa** [comment]
@gool123456, when you open up a bigendian database in IDA, does the database.config.info.lflags have their 5th bit set (`database.config.info.lflags & 0x20 == 0x20`)? Little-endian database should have that flag set to 0 (`database.config.info.lflags & 0x20 == 0`). I think that IDAPython just didn't define that flag, but it's likely that it's still available in the idainfo structure.

**Comment by arizvisa** [comment]
okay, try PR #111 again. I found an archive of the older IDA SDK and was able to figure out the correct way that IDA 5.6 determines the byteorder, kernelmode, etc.

**Comment by gool123456** [comment]
> 
> 
> okay, try PR #111 again. I found an archive of the older IDA SDK and was able to figure out the correct way that IDA 5.6 determines the byteorder, kernelmode, etc. So, this should work on your version of IDA 6.8.

@arizvisa HaHa,  Hey Crazy !! It's really amazing. These problems have been broken one by one. At present, this version has found a small problem. When using db.name to set the name, there will be no flags. 7.2 You need to use db.name('hskyre',flags=idaapi .GN_INSNLOC), 6.8 ver. Setting GN_INSNLOC flags seems to be invalid. The previous version will default to Include in names list flags. Is this a problem, or am I using it incorrectly? 👍

**Comment by arizvisa** [comment]
According to Ilfak whom wrote IDA, the `idaapi.GN_xxxxx` flag are for "Getting Names", and the "idaapi.SN_xxxxx" are for "Setting Names". To include the names in the names list, you'd need the `idaapi.SN_NOLIST` flag to be set to 0. However, you should be able to use `database.name('TestName', listed=True)`.

Is PR #111 okay to merge, or are there any more issues?

**Comment by gool123456** [comment]
> 
> 
> According to Ilfak whom wrote IDA, the `idaapi.GN_xxxxx` flag are for "Getting Names", and the "idaapi.SN_xxxxx" are for "Setting Names". To include the names in the names list, you'd need the `idaapi.SN_NOLIST` flag to be set to 0. However, you should be able to use `database.name('TestName', listed=True)`.
> 
> Is PR #111 okay to merge, or are there any more issues?

Haha, perfect, no problem at all !!

**Comment by arizvisa** [comment]
Okay. Closing this issue as PR #111 was merged.

Lmk if you encounter any other issues.
